/**
 * GENERATED BY build/gen-c-opcodes.ts
 * Sun, 23 Jul 2017 19:18:59 GMT
 * Revision 97e1439
 **/
static const int NOP = 0;
static const int CONST_I32 = 1;
static const int ADD_I32 = 16;
static const int SUB_I32 = 17;
static const int MUL_I32 = 18;
static const int DIV_I32 = 19;
static const int MOD_I32 = 20;
static const int EQ_I32 = 48;
static const int NE_I32 = 49;
static const int LT_I32 = 50;
static const int GT_I32 = 51;
static const int LTE_I32 = 52;
static const int GTE_I32 = 53;
static const int HALT = 80;
static const int CALL = 81;
static const int JMP = 82;
static const int JMP_F = 84;
static const int JNE_I32 = 85;
static const int STORE_G_I32 = 96;
static const int LOAD_G_I32 = 97;
static const int PRINT_I32 = 112;

/**
 * End generated file
 **/
