/**
 * GENERATED BY build/gen-c-opcodes.ts
 * Sat, 06 May 2017 16:41:41 GMT
 * Revision 821fe6c
 **/
static const int ICONST = 0x00;
static const int IADD = 0x01;
static const int PRINT = 0x02;
static const int GSTORE = 0x03;
static const int GLOAD = 0x04;
static const int JMP = 0x05;
static const int HALT = 0x06;
static const int JNE = 0x07;
static const int EQ = 0x08;
static const int NE = 0x09;
static const int LT = 0x0a;
static const int GT = 0x0b;
static const int LTE = 0x0c;
static const int GTE = 0x0d;

/**
 * End generated file
 **/
